= CONO-PLI Web Server API DOCS
CONO PLI
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[CONO-PLI-Auth]]
== 1. Auth Controller


[[Auth-Login-Post]]
=== 1.1 로그인

NOTE: 로그인 요청 API

operation::loginOk[snippets='http-request,request-fields,request-body,http-response,response-headers']


[[Auth-Verify-Login]]
=== 1.2 로그인 여부 확인

NOTE: 로그인 여부 확인 요청 API

operation::verifyUserOk[snippets='http-request,request-headers,http-response']


[[Auth-Verify-Login-Exception]]
=== 1.3 로그인 여부 확인 - 토큰 만료

NOTE: 로그인 여부 확인시 AccessToken 만료 경우 응답

operation::verifyUserException[snippets='http-request,request-headers,http-response,response-body,response-fields']

[[Auth-Reissue-Token]]
=== 1.4 토큰 재발급 OK

NOTE: AccessToken 재발급 요청 API

operation::refreshOk[snippets='http-request,path-parameters,http-response,response-body,response-fields']

[[Auth-Reissue-Token-Exception]]
=== 1.5 토큰 재발급 RefreshToken 만료

NOTE: AccessToken 재발급시 RefreshToken 만료 경우 응답

operation::refreshExpired[snippets='http-request,path-parameters,http-response,response-body,response-fields']


[[Auth-Logout]]
=== 1.6 로그아웃

NOTE: 로그아웃 요청 API

operation::verifyUserOk[snippets='http-request,request-headers,http-response']


[[CONO-PLI-User]]
== 2. User Controller


[[User-Get]]
=== 2.1 회원 정보 조회

NOTE: 특정 회원 정보 요청 API

operation::searchUser[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']


[[User-Delete]]
=== 2.2 회원 삭제

NOTE: 특정 회원 삭제(비활성화) 요청 API

operation::deleteUser[snippets='http-request,request-headers,path-parameters,http-response']



[[CONO-PLI-Search]]
== 3. Search Controller

[[Search-Music]]
=== 3.1 음악 검색

NOTE: 음악 검색 요청 API

operation::searchMusic[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']


[[Popular-Music]]
=== 3.2 인기곡 검색

NOTE: 인기곡 검색 요청 API

operation::popularMusic[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']


[[New-Music]]
=== 3.3 신곡 조회

NOTE: 신곡 리스트 조회 요청 API

operation::newMusic[snippets='http-request,http-response,response-body,response-fields']



[[CONO-PLI-User-Music]]
== 4. UserMusic Controller


[[User-Playlist-Get]]
=== 4.1 회원 플레이 리스트 조회

NOTE: 특정 회원의 플레이 리스트 요청 API

operation::userPlaylist[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']


[[User-Playlist-Music-Get]]
=== 4.2 플레이 리스트의 음악 조회

NOTE: 특정 플레이 리스트의 저장된 음악 리스트 요청 API

operation::userMusic[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']


[[User-Playlist-Post]]
=== 4.3 플레이 리스트 생성

NOTE: 특정 회원의 플레이 리스트 생성 요청 API

operation::savePlaylist[snippets='http-request,request-headers,request-body,http-response,response-body,response-fields']

[[User-Playlist-Music-Post]]
=== 4.4 플레이 리스트에 음악 저장

NOTE: 특정 플레이 리스트의 음악 저장 요청 API

operation::saveUserMusic[snippets='http-request,request-headers,request-body,request-fields,http-response,response-body,response-fields']


[[User-Playlist-Patch]]
=== 4.5 플레이 리스트 수정

NOTE: 특정 회원의 플레이 리스트 수정 요청 API

operation::modifyPlayList[snippets='http-request,request-headers,path-parameters,request-body,request-fields,http-response,response-body,response-fields']

[[User-Playlist-Music-Patch]]
=== 4.6 플레이 리스트의 저장 음악 수정

NOTE: 특정 플레이 리스트의 저장된 음악 수정 요청 API

operation::modifyUserMusic[snippets='http-request,request-headers,request-body,request-fields,http-response,response-body,response-fields']


[[User-Playlist-Duplication-Patch]]
=== 4.7 플레이 리스트 중복 음악 삭제

NOTE: 플레이 리스트 중복 음악 삭제 요청 API

operation::deleteDuplicationPlayList[snippets='http-request,request-headers,path-parameters,http-response']


[[User-Playlist-Delete]]
=== 4.8 플레이 리스트 삭제

NOTE: 플레이 리스트 삭제 요청 API

operation::deletePlayList[snippets='http-request,request-headers,path-parameters,http-response']

[[User-Playlist-Music-Delete]]
=== 4.9 플레이 리스트의 저장 음악 삭제

NOTE: 플레이 리스트에 저장된 음악 삭제 요청 API

operation::deleteUserMusic[snippets='http-request,request-headers,request-fields,http-response']