= CONO-PLI Web Server API DOCS
CONO PLI
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[overview]]
== Overview

[[overview-host]]
=== Host

|===
| 환경 | Host

| Develop
| `localhost`

| Production
| https://service.suyoung-server.site
|===


[[overview-error-codes]]
=== Error codes

|===
| 상태 코드 | 에러 코드 | 설명

| `400`
| `14001`
| BAD REQUEST

| `400`
| `14003`
| Already Exist User Email

| `400`
| `14004`
| Already Exist User Music

| `400`
| `14005`
| Argument Mismatch Bad Request

| `403`
| `14006`
| ACCESS DENIED

| `403`
| `14007`
| Inactive User

| `404`
| `14008`
| NOT FOUND

| `404`
| `14009`
| Not Found Request Url

| `404`
| `14010`
| Not Found User

| `404`
| `14011`
| Not Found User Music

| `404`
| `14012`
| Not Found Playlist

| `403`
| `14013`
| EXPIRED ACCESS TOKEN

| `404`
| `14014`
| TOKEN_NOT_NULL

| `401`
| `14015`
| EXPIRED REFRESH TOKEN

| `400`
| `14016`
| Music Domain Server Request I/O Error(Bad Request)


| `400`
| `14017`
| OAuth Server Request I/O Error(Bad Request)

| `500`
| `15001`
| Internal Server Error

| `500`
| `15002`
| Data Access Error

| `501`
| `15003`
| NOT IMPLEMENTED


|===

[[CONO-PLI-Auth]]
== 1. Auth Controller


[[Auth-Login-Post]]
=== 1.1 로그인

NOTE: 로그인 요청 API

operation::loginOk[snippets='http-request,request-fields,request-body,http-response,response-headers']

[[Auth-Login-Post-Exist]]
=== 1.2 로그인 실패 - Exist

NOTE: 로그인 실패 400

operation::loginExist[snippets='http-request,request-fields,request-body,http-response,response-headers']


[[Auth-Login-Post-Inactive]]
=== 1.3 로그인 실패 - Inactive

NOTE: 로그인 실패 403

operation::loginInactive[snippets='http-request,request-fields,request-body,http-response,response-headers']


[[Auth-Verify-Login]]
=== 1.4 로그인 여부 확인

NOTE: 로그인 여부 확인 요청 API

operation::verifyUserOk[snippets='http-request,request-headers,http-response']


[[Auth-Verify-Login-Exception]]
=== 1.5 로그인 여부 확인 - 토큰 만료

NOTE: 로그인 여부 확인시 AccessToken 만료 경우 응답

operation::verifyUserException[snippets='http-request,request-headers,http-response,response-fields']

[[Auth-Reissue-Token]]
=== 1.6 토큰 재발급 OK

NOTE: AccessToken 재발급 요청 API

operation::refreshOk[snippets='http-request,path-parameters,http-response,response-fields']

[[Auth-Reissue-Token-Exception]]
=== 1.7 토큰 재발급 RefreshToken 만료

NOTE: AccessToken 재발급시 RefreshToken 만료 경우 응답

operation::refreshExpired[snippets='http-request,path-parameters,http-response,response-fields']


[[Auth-Logout]]
=== 1.8 로그아웃

NOTE: 로그아웃 요청 API

operation::verifyUserOk[snippets='http-request,request-headers,http-response']


[[CONO-PLI-User]]
== 2. User Controller


[[User-Get]]
=== 2.1 회원 정보 조회

NOTE: 특정 회원 정보 요청 API

operation::searchUser[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


[[User-ReActivation]]
=== 2.2 탈퇴 회원 재 활성화

NOTE: 비활성 회원 재활성화 요청

operation::reActivationUser[snippets='http-request,request-fields,http-response,response-headers,response-fields']


[[User-Delete]]
=== 2.3 회원 삭제

NOTE: 특정 회원 삭제(비활성화) 요청 API

operation::deleteUser[snippets='http-request,request-headers,path-parameters,http-response']



[[CONO-PLI-Search]]
== 3. Search Controller

[[Search-Music]]
=== 3.1 음악 검색

NOTE: 음악 검색 요청 API

operation::searchMusic[snippets='http-request,query-parameters,http-response,response-fields']


[[Popular-Music]]
=== 3.2 인기곡 검색

NOTE: 인기곡 검색 요청 API

operation::popularMusic[snippets='http-request,query-parameters,http-response,response-fields']


[[New-Music]]
=== 3.3 신곡 조회

NOTE: 신곡 리스트 조회 요청 API

operation::newMusic[snippets='http-request,http-response,response-fields']



[[CONO-PLI-User-Music]]
== 4. UserMusic Controller


[[User-Playlist-Get]]
=== 4.1 회원 플레이 리스트 조회

NOTE: 특정 회원의 플레이 리스트 요청 API

operation::userPlaylist[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


[[User-Playlist-Music-Get]]
=== 4.2 플레이 리스트의 음악 조회

NOTE: 특정 플레이 리스트의 저장된 음악 리스트 요청 API

operation::userMusic[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


[[User-Playlist-Post]]
=== 4.3 플레이 리스트 생성

NOTE: 특정 회원의 플레이 리스트 생성 요청 API

operation::savePlaylist[snippets='http-request,request-headers,request-body,http-response,response-fields']

[[User-Playlist-Music-Post]]
=== 4.4 플레이 리스트에 음악 저장

NOTE: 특정 플레이 리스트의 음악 저장 요청 API

operation::saveUserMusic[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']


[[User-Playlist-Patch]]
=== 4.5 플레이 리스트 수정

NOTE: 특정 회원의 플레이 리스트 수정 요청 API

operation::modifyPlayList[snippets='http-request,request-headers,path-parameters,request-body,request-fields,http-response,response-fields']

[[User-Playlist-Music-Patch]]
=== 4.6 플레이 리스트의 저장 음악 수정

NOTE: 특정 플레이 리스트의 저장된 음악 수정 요청 API

operation::modifyUserMusic[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']


[[User-Playlist-Duplication-Patch]]
=== 4.7 플레이 리스트 중복 음악 삭제

NOTE: 플레이 리스트 중복 음악 삭제 요청 API

operation::deleteDuplicationPlayList[snippets='http-request,request-headers,path-parameters,http-response']

[[User-Playlist-OrderNum-Reset-Patch]]
=== 4.8 플레이 리스트 OrderNum 초기화

NOTE: 플레이 리스트의 UserMusic OrderNum 필드를 정렬하여 Index 값으로 초기화 요청 API

operation::resetOrderNumPlayList[snippets='http-request,request-headers,path-parameters,http-response']


[[User-Playlist-Delete]]
=== 4.9 플레이 리스트 삭제

NOTE: 플레이 리스트 삭제 요청 API

operation::deletePlayList[snippets='http-request,request-headers,path-parameters,http-response']

[[User-Playlist-Music-Delete]]
=== 4.10 플레이 리스트의 저장 음악 삭제

NOTE: 플레이 리스트에 저장된 음악 삭제 요청 API

operation::deleteUserMusic[snippets='http-request,request-headers,request-fields,http-response']